name: Android CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'H2CO3_main'
  pull_request:
    branches:
      - 'H2CO3_main'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@main
        with:
           allow-snapshot-wrappers: true
           cache-read-only: false
        
      - name: Set up JDK
        uses: actions/setup-java@main
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Build Debug .apk
        run: |
            chmod +x ./gradlew
            ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@main
        with:
          name: H2CO3-debug
          path: H2CO3/build/outputs/apk/debug/*.apk
